AfshinBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from articles.views import article_list



app_name='AfshinBlog'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about, name='about'),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.home,name='homepage'),
    path('gallery/',include('gallery.urls')),
    path('comments/',include('comments.urls')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name= 'accounts'
urlpatterns = [
    path('signup',views.signup_view,name='signup'),
    path('login',views.login_view,name='login'),
    path('logout',views.logout_view,name='logout'),
]

articles/urls.py
from django.urls import path
from . import views


app_name = "articles"

urlpatterns = [
    path('',views.article_list, name="list"),
    path('create',views.create_article,name="create"),
    path('<slug>',views.articles_detail, name='detail'),
]

comments/urls.py
from django.urls import path
from . import views


app_name = "comments"

urlpatterns = [
    path('',views.comments, name="comments"),

]

gallery/urls.py
from django.urls import path
from . import views


app_name = "gallery"

urlpatterns = [
    path('',views.gallery_list, name="gallery_list"),
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default='default.jpg', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):

        return self.title

    def snippet(self):
        return self.body[:30]+'...'

comments/models.py
from django.db import models
from django.contrib.auth.models import User


class comments(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100, blank=True)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):

        return self.name

    def snippet(self):
        return self.body[0]+'...'

# Create your models here.

gallery/models.py
from django.db import models

# Create your models here.

articles/forms.py
from django import forms
from . import models
class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','slug','body','image']

comments/forms.py
from django import forms
from . import models
class commentsform(forms.ModelForm):
    class Meta:
        model = models.comments
        fields = ['name','email','body']

AfshinBlog/views.py
from django.shortcuts import render, HttpResponse
from comments import forms
from comments import models
from comments import urls



def home(request):
    comments = models.comments.objects.all().order_by('-date')
    args = {'comments':comments}
    return render(request,'home.html',args)
    # return HttpResponse('home')



def about(request):
    # return HttpResponse('about')
    return render(request, 'about.html')

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # user = form.save()
            # login(request, user)
            return redirect('accounts:login')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                 return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)

        return redirect('accounts:login')

articles/views.py
from django.shortcuts import render,HttpResponse,redirect
from . import models
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):
    # return HttpResponse("ARTICLES")
    articles = models.Article.objects.all().order_by('-date')
    args = {'articles':articles}
    return render(request,'articles/articleslist.html',args)

def articles_detail(request, slug):
    article = models.Article.objects.get(slug=slug)
    arg = {'article':article}
    return render(request,'articles/articles_detail.html',arg)
    # return HttpResponse(slug)
@login_required(login_url="/accounts/login")
def create_article(request):
    if request.method == "POST":
        form = forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit = False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request,'articles/create_article.html',{'form':form})

comments/views.py
from django.shortcuts import render,HttpResponse,redirect
from . import models
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
@login_required(login_url="/accounts/login")
def comments(request):

    if request.method == "POST":
        form = forms.commentsform(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit = False)
            instance.author = request.user
            instance.save()
            return redirect('homepage')
    else:
        form = forms.commentsform()
    return render(request,'comments/comments.html',{'form':form})

gallery/views.py
from django.shortcuts import render,HttpResponse

# Create your views here.
def gallery_list(request):
    return render(request,'gallery/gallery.html')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h3>LOGIN</h3>
  <strong>اگر عضو نیستید لطفا</strong>
  <strong>برای ورود ثبت نام کنید</strong>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">

  {{form}}
  {% csrf_token %}
  {% if request.GET.next %}
    <input type="hidden" name="next" value="{{request.GET.next}}">
  {% endif %}
  <button type="submit" name="submit">ورود</button>
  <a class="sabtenam" href="{% url 'accounts:signup' %}">ثبت نام</a>
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h3>singup</h3>
<form class="site-form" action="{% url 'accounts:signup' %}" method="post">
  {{form}}
  {% csrf_token %}
  <button type="submit" name="submit">signup</button>
</form>
{% endblock %}

articles/templates/articles/articles_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="article_detail">
  <div class="article">
    <img src="{{article.image.url}}" alt="مقاله">
    <h2>{{article.title}}</h2>
    <p>{{article.body}}</p>
    <h5>{{article.date}}</h5>
  </div>
</div>
{% endblock %}

articles/templates/articles/articleslist.html
{% extends 'base.html' %}

{% block title %}
      ARTICLE

{% endblock %}



    {% block content%}


    <h1>دست نویس</h1>
        <h3><a id="createlink" href="{% url 'articles:create' %}"><button id="benevis">تو برام بنویس!!!</button></a></h3>
        <div class="articles" >
    {% for article in articles %}
        <div class="article">
    <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
      <p>{{article.snippet}}</p>
      <p>{{article.date}}</p>
        <p class="author">{{ article.author.username }}</p>
        </div>
    {% endfor %}
</div>

{% endblock %}

articles/templates/articles/create_article.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<h1>ARTICLE creating</h1>
<form class="site-create" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
  {{form}}
  {% csrf_token %}
  <button class="bcreate" type="submit" name="button">  ثبت   </button>
</form>
    <script src="{% static 'slugify.js' %}"></script>
{% endblock %}

comments/templates/comments/comments.html
{% extends 'base.html' %}

{% block title%}
  comments
{% endblock %}



{% block content %}
<h1>نظرات</h1>

<form id="cont" class="site-create" action="{% url 'comments:comments' %}" method="post">
  {{form}}
  {% csrf_token %}
  <button class="bcreate" type="submit" name="button">  ثبت   </button>

{% endblock %}

gallery/templates/gallery/gallery.html
{% extends 'base.html' %}

{% block title %}

    gallery

{% endblock %}



    {% block content%}


    <h1>عکس بازیامون</h1>


{% endblock %}